### ISSUE TITLE
Issue running in container

### ISSUE THREAD

**Issue by Greylorn** [VirtualAE/Virtuals-Custom-Quest-Loader#6]
Trying to run SPT in an AMP container gives me this error. Works fine in local environment.

Press Enter to close the window
12:13:18
Commit hash: 002209a992253888d025344f831b28077a5210d1
Build date: 1720888332978
┌─────────────────────────────────────────┐
│ SPT 3.9.0 │
│ https://discord.sp-tarkov.com │
│ │
│ This work is free of charge │
│ If you paid money, you were scammed │
│ Commercial use is prohibited │
└─────────────────────────────────────────┘
ModLoader: loading: 16 server mods...
Mod: MultiplyALL version: 4.0.0 by: Alim Oncul loaded
Mod: Painter - Trader version: 1.0.8 by: MoxoPixel loaded
Mod: Bosses Have Lega Medals version: 1.0.0 by: acidphantasm loaded
Mod: RefSPTFriendlyQuests version: 1.1.0 by: acidphantasm loaded
Mod: Virtuals Custom Quest Loader version: 2.0.2 by: Virtual loaded
Mod: DoorBreacher version: 1.1.7 by: Props loaded
Mod: LiveFleaPrices version: 1.2.0 by: DrakiaXYZ loaded
Mod: server version: 2.2.1 by: Fika loaded
Mod: Gilded Key Storage version: 1.4.0 by: Jehree loaded
Mod: MoreCheckmarksBackend version: 1.5.14 by: VIP loaded
Mod: Black Core version: 1.1.1 by: MoxoPixel loaded
Mod: Mag Tape version: 1.0.6 by: MoxoPixel loaded
Mod: Tactical Gear Component (TGC) version: 1.1.1 by: MoxoPixel loaded
Mod: LootingBots-ServerMod version: 1.3.5 by: Skwizzy loaded
Mod: SWAG + DONUTS version: 3.5.0 by: nooky and props loaded
Mod: SAIN version: 3.0.1 by: Solarint loaded
The application had a critical error and failed to run
Exception produced: ReferenceError
Stacktrace:
ReferenceError: container is not defined
at Object.<anonymous> (/AMP/tarkov/server/user/mods/Virtual's Custom Quest Loader/src/mod.ts:6:1)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Module._compile (pkg/prelude/bootstrap.js:1894:32)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at Module.require (pkg/prelude/bootstrap.js:1851:31)
at require (node:internal/modules/helpers:176:18)
at PreSptModLoader.executeModsAsync (/snapshot/src/loaders/PreSptModLoader.ts:386:33)
12:15:08
Press Enter to close the window
12:15:12
ModLoader: loading: 16 server mods...
Mod: MultiplyALL version: 4.0.0 by: Alim Oncul loaded
Mod: Painter - Trader version: 1.0.8 by: MoxoPixel loaded
Mod: Bosses Have Lega Medals version: 1.0.0 by: acidphantasm loaded
Mod: RefSPTFriendlyQuests version: 1.1.0 by: acidphantasm loaded
Mod: Virtuals Custom Quest Loader version: 2.0.2 by: Virtual loaded
Mod: DoorBreacher version: 1.1.7 by: Props loaded
Mod: LiveFleaPrices version: 1.2.0 by: DrakiaXYZ loaded
Mod: server version: 2.2.1 by: Fika loaded
Mod: Gilded Key Storage version: 1.4.0 by: Jehree loaded
Mod: MoreCheckmarksBackend version: 1.5.14 by: VIP loaded
Mod: Black Core version: 1.1.1 by: MoxoPixel loaded
Mod: Mag Tape version: 1.0.6 by: MoxoPixel loaded
Mod: Tactical Gear Component (TGC) version: 1.1.1 by: MoxoPixel loaded
Mod: LootingBots-ServerMod version: 1.3.5 by: Skwizzy loaded
Mod: SWAG + DONUTS version: 3.5.0 by: nooky and props loaded
Mod: SAIN version: 3.0.1 by: Solarint loaded
The application had a critical error and failed to run
Exception produced: Error
Stacktrace:
Error: Cannot find module 'C:/snapshot/project/obj/models/enums/ConfigTypes'
Require stack:
- /AMP/tarkov/server/user/mods/Virtual's Custom Quest Loader/src/mod.js
- /snapshot/project/obj/loaders/PreSptModLoader.js
- /snapshot/project/obj/controllers/GameController.js
- /snapshot/project/obj/callbacks/GameCallbacks.js
- /snapshot/project/obj/di/Container.js
- /snapshot/project/obj/Program.js
- /snapshot/project/obj/ide/ReleaseEntry.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
at Function.Module._load (node:internal/modules/cjs/loader:985:27)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at Module.require (pkg/prelude/bootstrap.js:1851:31)
at require (node:internal/modules/helpers:176:18)
at Object.<anonymous> (/AMP/tarkov/server/user/mods/Virtual's Custom Quest Loader/src/mod.ts:6:1)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Module._compile (pkg/prelude/bootstrap.js:1894:32)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

**Comment by Greylorn** [comment]
delete .js and.js.map in the src folder of VCQL and associated mods and it will rebuild/work on linux.

**Comment by VirtualAE** [comment]
Future releases to exclude .js and .js.map files so the server can correctly transpile on startup. Thanks for raising the issue.
